### PR TITLE
Move to eslint-config-airbnb-base and fix CI

### PR DESCRIPTION
**Pull request by Arcanemagus**
There is no need for the React components of the full eslint-config-airbnb.

Closes #44.
Closes #45.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Something is _still_ wrong with the `golinter` setup on the Travis Linux builds...

**Comment by kavu** [comment]
@Arcanemagus Travis Linux builds use old Go version, which doesn't have `go/types` package. I am not sure how, but you can try to add somewhere here https://github.com/AtomLinter/linter-golinter/blob/29afbab6a04bdd4528469f9ec7ee0e6474a0c2a1/.travis.yml#L5 and https://github.com/AtomLinter/linter-golinter/blob/29afbab6a04bdd4528469f9ec7ee0e6474a0c2a1/.travis.yml#L7 there requirement of Go version 1.6.

**Comment by kavu** [comment]
@Arcanemagus done, see #48

**Comment by Arcanemagus** [comment]
Oh, you did #48 as a PR to this branch, why didn't you just commit here? :stuck_out_tongue:

That's the whole reason I do branches on the main repo so everyone can work on them :wink:.

**Pull request merged**
